### ISSUE TITLE
[GLOBAL] Discussione sul nome finale del prodotto

### ISSUE THREAD

**Issue by Maxelweb** [RedRoundRobin/swe-thirema#15]
Come ci era stato consigliato dal professor Vardanega, si potrebbe tirare fuori un nuovo nome del prodotto in vista della futura RQ/RA. In sostanza, si rimane _Project ThiReMa_ come progetto interno e si cambierà nome alla presentazione finale del prodotto.
Se avete proposte interessanti postatele di seguito.

- qIoTo = Quality IoT Ontology
- IoTon = IoT Ontology Network
- ManyThings

**Comment by BroHPotato** [comment]
ReMOTO  - Remote Management Of Things Ontology

**Comment by Maxelweb** [comment]
Riot

**Comment by Maxelweb** [comment]
![riot](https://i.imgur.com/Krg1LRG.png)

Confermato.
