### ISSUE TITLE
Decisione sulla licenza del prodotto

### ISSUE THREAD

**Issue by Maxelweb** [RedRoundRobin/swe-thirema#18]
Dobbiamo decidere la licenza del prodotto. Ci conviene spulciare grosso modo tutte le librerie di cui facciamo uso (o anche solo i framework) per trovare bene una licenza compatibile.
Attenzione anche alle immagini docker, specie quelle di Kafka.

**Comment by M9k** [comment]
Buongiorno, tenete in considerazione che se non ridistribuite le dipendenze e se non le modificate non siete sempre costretti a licenziare con una licenza compatibile. Il discorso è abbastanza spinoso, ad esempio molti software closed suorce vengono distribuiti in bundle con Linux senza essere GPL.
